#!/bin/bash
set -e

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║         Spec-Drift Chronometer — Dev Launcher           ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Defaults ──────────────────────────────────────────────────────────────────
export DEMO_MODE="${DEMO_MODE:-true}"
export DRIFT_THRESHOLD="${DRIFT_THRESHOLD:-0.0075}"
BACKEND_PORT="${BACKEND_PORT:-8000}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"

echo "  DEMO_MODE        = $DEMO_MODE"
echo "  DRIFT_THRESHOLD  = $DRIFT_THRESHOLD"
echo "  Backend port     = $BACKEND_PORT"
echo "  Frontend port    = $FRONTEND_PORT"
echo ""

# ── Cleanup on Ctrl+C ─────────────────────────────────────────────────────────
cleanup() {
    echo ""
    echo "Shutting down Spec-Drift Chronometer..."
    kill "$BACKEND_PID" "$FRONTEND_PID" 2>/dev/null || true
    sleep 1
    kill -9 "$BACKEND_PID" "$FRONTEND_PID" 2>/dev/null || true
    echo "System offline."
    exit 0
}
trap cleanup INT TERM

# ── Python virtual environment ─────────────────────────────────────────────────
echo "[1/4] Setting up Python environment..."
cd "$PROJECT_ROOT"
if [ ! -d "venv" ]; then
    python3 -m venv venv
fi
# shellcheck disable=SC1091
source venv/bin/activate
pip install -r backend/requirements.txt --quiet

# ── Backend ────────────────────────────────────────────────────────────────────
echo "[2/4] Starting Warden Engine (backend) on port $BACKEND_PORT..."
cd "$PROJECT_ROOT/backend"
python -m uvicorn main:app --host 0.0.0.0 --port "$BACKEND_PORT" --reload > "$PROJECT_ROOT/backend.log" 2>&1 &
BACKEND_PID=$!
cd "$PROJECT_ROOT"

# Wait for backend to be ready
echo "      Waiting for backend..."
for i in $(seq 1 15); do
    if curl -sf "http://localhost:${BACKEND_PORT}/drift" > /dev/null 2>&1; then
        echo "      Backend LIVE at http://localhost:${BACKEND_PORT}"
        break
    fi
    sleep 1
    if [ "$i" -eq 15 ]; then
        echo "      WARNING: Backend did not start in 15s. Check backend.log for errors."
    fi
done

# ── Frontend env ───────────────────────────────────────────────────────────────
echo "[3/4] Writing frontend environment..."
cat > "$PROJECT_ROOT/frontend/.env.local" <<EOF
# Auto-generated by dev.sh — edit for production
NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}
EOF

# ── Frontend ───────────────────────────────────────────────────────────────────
echo "[4/4] Starting Dashboard (frontend) on port $FRONTEND_PORT..."
cd "$PROJECT_ROOT/frontend"
if [ ! -d "node_modules" ]; then
    echo "      Installing frontend dependencies (first run only)..."
    npm install --quiet
fi
npm run dev -- --port "$FRONTEND_PORT" > "$PROJECT_ROOT/frontend.log" 2>&1 &
FRONTEND_PID=$!
cd "$PROJECT_ROOT"

# Brief pause for Next.js to start compiling
sleep 3

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  System is LIVE                                          ║"
echo "║                                                          ║"
echo "║  Dashboard   →  http://localhost:${FRONTEND_PORT}              ║"
echo "║  Backend API →  http://localhost:${BACKEND_PORT}              ║"
echo "║                                                          ║"
echo "║  Logs: backend.log | frontend.log                       ║"
echo "║  Press [CTRL+C] to stop all services.                   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

wait
